# Generated by Django 4.2 on 2025-11-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmpresaPersonaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tidoc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tidoc_tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'TIPO_DOCUMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('tpago_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tpago_tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TIPO_PAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('tipo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_trans', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'TIPO_TRANSACCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleDoc',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('dedoc_cant', models.PositiveIntegerField()),
                ('dedoc_obs', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'DETALLE_DOC',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('docum_num', models.AutoField(primary_key=True, serialize=False)),
                ('docum_estado', models.CharField(max_length=20)),
                ('docum_fecha_emi', models.DateField()),
                ('docum_fecha_ven', models.DateField(blank=True, null=True)),
                ('docum_fecha_recl', models.DateField(blank=True, null=True)),
                ('docum_obs', models.CharField(blank=True, max_length=200)),
                ('empresa', models.ForeignKey(db_column='EMPPE_ID', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='EmpresaPersonaApp.empresapersona')),
            ],
            options={
                'db_table': 'DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_fecha', models.DateField()),
                ('trans_monto', models.IntegerField()),
                ('documento', models.ForeignKey(db_column='DOCUM_NUM', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='FacturacionApp.documento')),
                ('tipo', models.ForeignKey(db_column='TIPO_ID', on_delete=django.db.models.deletion.PROTECT, to='FacturacionApp.tipotransaccion')),
            ],
            options={
                'db_table': 'TRANSACCION',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('fpago_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpago_dias', models.IntegerField()),
                ('tipo_pago', models.ForeignKey(db_column='TPAGO_ID', on_delete=django.db.models.deletion.PROTECT, to='FacturacionApp.tipopago')),
            ],
            options={
                'db_table': 'FORMA_PAGO',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='forma_pago',
            field=models.ForeignKey(db_column='FPAGO_ID', on_delete=django.db.models.deletion.PROTECT, to='FacturacionApp.formapago'),
        ),
    ]
