# Generated by Django 4.2 on 2025-11-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProyectoApp', '0001_initial'),
        ('ProductoServicioApp', '0001_initial'),
        ('FacturacionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_column='PROYE_IDT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='ProyectoApp.proyecto'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_doc',
            field=models.ForeignKey(db_column='TIDOC_ID', on_delete=django.db.models.deletion.PROTECT, to='FacturacionApp.tipodocumento'),
        ),
        migrations.AddField(
            model_name='detalledoc',
            name='documento',
            field=models.ForeignKey(db_column='DOCUM_NUM', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='FacturacionApp.documento'),
        ),
        migrations.AddField(
            model_name='detalledoc',
            name='producto',
            field=models.ForeignKey(db_column='PRODU_ID', on_delete=django.db.models.deletion.PROTECT, to='ProductoServicioApp.productoservicio'),
        ),
    ]
