# Generated by Django 4.2.16 on 2025-12-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacturacionApp', '0003_detalledoc_dedoc_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='docum_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('MITAD', 'Pagado Mitad'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('docum_num', 'tipo_doc'), name='unique_docum_num_por_tipo'),
        ),
    ]
